services:
  - type: web
    name: messagejs-api
    env: node
    buildCommand: cd ../.. && npm install && npm run build --workspace=@messagejs/shared-types && npm run build --workspace=packages/core && cd packages/core && npx prisma generate
    startCommand: npm start
    rootDir: packages/core

  - type: worker
    name: messagejs-worker
    env: node
    buildCommand: cd ../.. && npm install && npm run build --workspace=@messagejs/shared-types && npm run build --workspace=packages/core && cd packages/core && npx prisma generate
    startCommand: npm run start:worker
    rootDir: packages/core
